import type { Config } from "tailwindcss";

// Tokens copied verbatim from the uploaded Stitch export's
// clinical_precision/DESIGN.md and the inline tailwind.config found in
// every exported code.html. Do not "improve" or reinterpret these values —
// the brief is pixel parity with the original export.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#003ea8",
        background: "#f7f9fb",
        "on-surface-variant": "#434655",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-container": "#eeefff",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00788c",
        "outline-variant": "#c3c6d7",
        "on-tertiary-fixed": "#001f26",
        "on-secondary-container": "#00714d",
        "primary-fixed-dim": "#b4c5ff",
        "primary-container": "#2563eb",
        surface: "#f7f9fb",
        primary: "#004ac6",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed-variant": "#004e5c",
        secondary: "#006c49",
        "surface-tint": "#0053db",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "inverse-primary": "#b4c5ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "on-surface": "#191c1e",
        "primary-fixed": "#dbe1ff",
        "surface-bright": "#f7f9fb",
        error: "#ba1a1a",
        "on-primary-fixed": "#00174b",
        "secondary-fixed": "#6ffbbe",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#4cd7f6",
        "secondary-container": "#6cf8bb",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#d7f6ff",
        tertiary: "#005e6e",
        "tertiary-fixed": "#acedff",
        "surface-container-low": "#f2f4f6",
        outline: "#737686",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        gutter: "24px",
        xl: "32px",
        xxl: "48px",
      },
      maxWidth: {
        container: "1280px",
      },
      boxShadow: {
        "level-2": "0 10px 15px -3px rgba(0, 0, 0, 0.05), 0 4px 6px -2px rgba(0, 0, 0, 0.02)",
        "level-3": "0 12px 20px -4px rgba(0, 0, 0, 0.08), 0 6px 8px -3px rgba(0, 0, 0, 0.03)",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/forms")],
};

export default config;
